[workspace]
members = ["crates/cavalre-ledgers-kernel", "crates/cavalre-ledgers-core", "crates/cavalre-ledgers-solana", "tests/integration", "tests/solana-consumer"]
default-members = ["crates/cavalre-ledgers-kernel", "crates/cavalre-ledgers-core"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.89"
publish = false
repository = "https://github.com/CavalRe/cavalre-ledgers"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
